# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 469e3fc16fcf2b748eee2f1eb81f3c771168e8e313391716461d7136d007ef2777f4ca9e88165aaa9ca18b98f23f39d855eab392edaeb8baa5b6a1b9160458fa

test:
  secret_key_base: 489750371d3424bd4f026478921be6262cdce7bfd44d1375fe9ed2e414fb332a3d864e8bdd943ae82c3adb5495bbbe2a4661c171240c005162ce225afd335cb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
